### ISSUE TITLE
Extend metadata

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-plants-belgium#30]

**Comment by peterdesmet** [comment]
What I did:

* Set update frequency to biannually
* Added 3 authors (resource creators): Filip, Quentin, Peter
* Added kingdom "Plantae" to taxonomic coverage
* Kept subkingdom "Angiospermae" (but used scientific name, not Angiosperms)
* Removed project personnel: I would keep this section empty (it's often duplicating methods information)
* Set automatic citation (including DOI)

There is no now metadata information I consider incorrect (except collection info, see further)

## Todo

- [x]  Add description
- [x] Extend geographic coverage (maybe)
- [x] Extend taxonomic coverage (it's about invasive)
- [x] Is there a temporal range? **We limited this to the date of first observation and the last update of the MAP**
- [x] Add keywords
- [x] Add sampling information (include reference to this GitHub repo): **We refer to Verloove (2006) for a detailed description of the sampling method. We do elaborate more on our working procedure, with a referene to the GitHub repo (See Methodology section)**
- [x] Add bibliographic information
- [x] Not sure we need to add collection information here? This resource does not describe a collection, even though it might be based on collection information **We describe that the MAP is almost entirely based on herbarium revision and refer to Verloove et al. (2006) for more information. As I remember it correctly, we decided to leave out further information on the collections.**

See http://data.canadensys.net/ipt/resource.do?r=vascan as an example

The data files have been updated with the most recent version (September 16)

**Comment by LienReyserhove** [comment]
For my answers, see **bold** text in the previous  comment.
The metadata have been extended, see the [GBIF page](https://www.gbif.org/dataset/9ff7d317-609b-4c08-bd86-3bc404b77c42) for the Manual of Alien Plants.

I'm closing this issue.
